[tool.poetry]
name = "pythcat"
version = "0.1.0"
description = "Python package to ease EDA for Catogorical variables"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
